import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebar configuration for Docusaurus documentation
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'intro', // points to docs/intro.md
      label: 'Introduction',
      className: 'sidebar-icon--book',
    },
    {
      type: 'category',
      label: 'General',
      className: 'sidebar-icon--folder',
      items: [
        {
          type: 'autogenerated',
          dirName: 'general', // folder: docs/general/
        },
      ],
    },
    {
      type: 'category',
      label: 'Flight Information',
      className: 'sidebar-icon--book',
      items: [
        {
          type: 'autogenerated',
          dirName: 'flight-information', // folder: docs/flight-information/
        },
      ],
    },
    {
      type: 'category',
      label: 'Aircraft Operations',
      className: 'sidebar-icon--paper',
      items: [
        {
          type: 'autogenerated',
          dirName: 'aircraft-operations', // folder: docs/aircraft-operations/
        },
      ],
    },
    {
      type: 'category',
      label: 'Airspace Restrictions',
      className: 'sidebar-icon--book',
      items: [
        {
          type: 'autogenerated',
          dirName: 'airspace-restrictions',
        },
      ],
    },
    {
      type: 'category',
      label: 'Penalty Points Summary',
      className: 'sidebar-icon--paer',
      items: [
        {
          type: 'autogenerated',
          dirName: 'penalty-points-summary',
        },
      ],
    },
    {
      type: 'category',
      label: 'Professional Conduct',
      className: 'sidebar-icon--book',
      items: [
        {
          type: 'autogenerated',
          dirName: 'professional-conduct',
        },
      ],
    },
  ],
};

export default sidebars;
