import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
      className: 'sidebar-icon--book',
    },
    {
      type: 'category',
      label: 'GENERAL',
      className: 'sidebar-icon--folder',
      items: [
        {
          type: 'autogenerated',
          dirName: 'GENERAL',
        },
      ],
    },
    {
      type: 'category',
      label: 'INTRODUCTION',
      className: 'sidebar-icon--paper',
      items: [
        {
          type: 'autogenerated',
          dirName: 'INTRODUCTION',
        },
      ],
    },
    {
      type: 'category',
      label: 'FLIGHT INFORMATION',
      className: 'sidebar-icon--book',
      items: [
        {
          type: 'autogenerated',
          dirName: 'INTRODUCTION',
        },
      ],
    },
  ],
};

export default sidebars;
